# Generated by Django 5.0.6 on 2024-05-22 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idrecord",
            old_name="author",
            new_name="date",
        ),
    ]
