# Generated by Django 5.0.6 on 2024-05-23 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_author_idrecord_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idrecord",
            name="date",
        ),
    ]
