# Generated by Django 5.0.6 on 2024-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_idrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idrecord",
            name="id_value",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
